FROM node:8.17 as build-deps
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn
COPY . ./
RUN yarn build

FROM nginx:1.17.8-alpine
COPY --from=build-deps /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# FROM node:10

# RUN mkdir -p /app/src/client

# COPY ./package.json /app
# COPY ./package-lock.json /app
# COPY ./params.js /app
# COPY ./webpack.config.js /app
# COPY ./index.html /app
# COPY ./src/client /app/src/client

# WORKDIR /app

# RUN npm install

# EXPOSE 8080

# CMD npm run client-dev
