#############################################################
#			NEED TO BE UPDATE FOR NEW IMPLEMENTATION
#############################################################
# version: "3.3"
# services:
#   database:
#     image: mongo:latest
#     ports:
#       - 27017:27017
#     networks:
#       - project
      
#   client:
#     build:
#       context: .
#       dockerfile: client/dockerfile-cli
#     ports:
#       - 8080:8080
#     volumes:
# 	  - "./client/src:/app/src/client"
#     networks:
#       - project

#   server:
#     build:
#       context: .
#       dockerfile: dockerfile-srv
#     ports:
#       - 3004:3004
#     volumes:
#       - "./src/server:/app/src/server"
#     networks:
#       - project
      
# networks:
#   project:
