FROM node:8.17 as builds-deps
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn
COPY . ./
RUN yarn build

FROM nginx:1.17.8-alpine
COPY --from=builds-deps /usr/src/app/build /usr/share/nginx/html
EXPOSE 3004
CMD ["nginx", "-g", "daemon off;"]

